version: '3'
services:
  mongodb:
    image: mongo:5
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db


#url: mongodb://root:root@localhost:27017